-- Initial schema: generated from live Postgres database 2026-04-04
-- This migration is only applied to empty databases.
-- Existing databases already have this schema from sqlite_to_postgres.py.
CREATE TABLE IF NOT EXISTS public.app_settings (
    key text NOT NULL,
    value text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.audit_events (
    id bigint NOT NULL,
    occurred_at_ms bigint NOT NULL,
    actor_user_id bigint,
    actor_username text NOT NULL,
    actor_role text NOT NULL,
    actor_auth_type text NOT NULL,
    method text NOT NULL,
    path text NOT NULL,
    status_code bigint NOT NULL,
    remote_host text DEFAULT ''::text NOT NULL,
    detail text DEFAULT ''::text NOT NULL,
    garden_id bigint DEFAULT 1
);
ALTER TABLE public.audit_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.audit_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.auth_mfa_pending_enrollments (
    user_id bigint NOT NULL,
    secret_ciphertext text NOT NULL,
    created_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS public.auth_mfa_recovery_codes (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    code_hash text NOT NULL,
    created_at_ms bigint NOT NULL,
    used_at_ms bigint
);
ALTER TABLE public.auth_mfa_recovery_codes ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_mfa_recovery_codes_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.auth_password_reset_tokens (
    id bigint NOT NULL,
    token_hash text NOT NULL,
    user_id bigint NOT NULL,
    created_by_user_id bigint,
    created_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    used_at_ms bigint,
    used_by_user_id bigint,
    metadata text DEFAULT ''::text NOT NULL
);
ALTER TABLE public.auth_password_reset_tokens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_password_reset_tokens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.auth_sessions (
    token_hash text NOT NULL,
    user_id bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    created_at_ms bigint NOT NULL,
    last_seen_at_ms bigint NOT NULL,
    reauthenticated_at_ms bigint DEFAULT 1 NOT NULL,
    mfa_authenticated_at_ms bigint DEFAULT 0 NOT NULL,
    mfa_setup_required bigint DEFAULT 0 NOT NULL
);
CREATE TABLE IF NOT EXISTS public.auth_user_invitations (
    id bigint NOT NULL,
    invitee_username text NOT NULL,
    role text NOT NULL,
    token_hash text NOT NULL,
    created_by_user_id bigint,
    created_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    accepted_at_ms bigint,
    accepted_user_id bigint,
    revoked_at_ms bigint
);
ALTER TABLE public.auth_user_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_user_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.auth_user_plot_assignment_meanings (
    user_id bigint NOT NULL,
    pattern text NOT NULL,
    label text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    created_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
    updated_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.auth_users (
    id bigint NOT NULL,
    username text NOT NULL,
    password_hash text NOT NULL,
    role text NOT NULL,
    is_active bigint DEFAULT 1 NOT NULL,
    created_by_user_id bigint,
    must_change_password bigint DEFAULT 0 NOT NULL,
    deactivated_at text,
    deactivated_reason text,
    created_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
    last_login_at text,
    shademap_api_key text,
    mfa_totp_secret text,
    mfa_totp_enabled bigint DEFAULT 0 NOT NULL,
    mfa_enrolled_at text,
    language text DEFAULT 'en'::text NOT NULL,
    last_totp_counter bigint DEFAULT 0 NOT NULL,
    subscription_tier text DEFAULT 'home'::text NOT NULL
);
ALTER TABLE public.auth_users ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.auth_users_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.garden_invitations (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    invitee_username text NOT NULL,
    role text NOT NULL,
    token_hash text NOT NULL,
    created_by_user_id bigint,
    created_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    accepted_at_ms bigint,
    accepted_user_id bigint,
    revoked_at_ms bigint
);
ALTER TABLE public.garden_invitations ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.garden_invitations_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.garden_issue_plants (
    issue_id bigint NOT NULL,
    plt_id text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.garden_issue_plots (
    issue_id bigint NOT NULL,
    plot_id text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.garden_issues (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    issue_type text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    severity text DEFAULT 'normal'::text NOT NULL,
    status text DEFAULT 'open'::text NOT NULL,
    suspected_cause text DEFAULT ''::text NOT NULL,
    treatment_plan text DEFAULT ''::text NOT NULL,
    follow_up_on text,
    metadata_json text DEFAULT '{}'::text NOT NULL,
    created_by_user_id bigint,
    resolved_by_user_id bigint,
    resolved_at_ms bigint,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL
);
ALTER TABLE public.garden_issues ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.garden_issues_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.garden_journal_entries (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    event_type text NOT NULL,
    occurred_on text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    notes text DEFAULT ''::text NOT NULL,
    metadata_json text DEFAULT '{}'::text NOT NULL,
    actor_user_id bigint,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL
);
ALTER TABLE public.garden_journal_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.garden_journal_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.garden_journal_entry_plants (
    entry_id bigint NOT NULL,
    plt_id text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.garden_journal_entry_plots (
    entry_id bigint NOT NULL,
    plot_id text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.garden_memberships (
    garden_id bigint NOT NULL,
    user_id bigint NOT NULL,
    role text NOT NULL,
    created_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.garden_task_plants (
    task_id bigint NOT NULL,
    plt_id text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.garden_task_plots (
    task_id bigint NOT NULL,
    plot_id text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.garden_tasks (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    task_type text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'pending'::text NOT NULL,
    severity text DEFAULT 'normal'::text NOT NULL,
    due_on text NOT NULL,
    snoozed_until text,
    rule_source text DEFAULT ''::text NOT NULL,
    metadata_json text DEFAULT '{}'::text NOT NULL,
    created_by_user_id bigint,
    completed_by_user_id bigint,
    completed_at_ms bigint,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL
);
ALTER TABLE public.garden_tasks ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.garden_tasks_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.gardens (
    id bigint NOT NULL,
    slug text NOT NULL,
    name text NOT NULL,
    created_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
    grid_rows bigint DEFAULT 30 NOT NULL,
    grid_cols bigint DEFAULT 22 NOT NULL,
    latitude double precision,
    longitude double precision,
    address text DEFAULT ''::text,
    onboarding_complete bigint DEFAULT 0 NOT NULL,
    owner_user_id bigint
);
ALTER TABLE public.gardens ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.gardens_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.harvest_entries (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    occurred_on text NOT NULL,
    quantity double precision DEFAULT 0 NOT NULL,
    unit text DEFAULT 'kg'::text NOT NULL,
    quality text DEFAULT 'good'::text NOT NULL,
    notes text DEFAULT ''::text NOT NULL,
    metadata_json text DEFAULT '{}'::text NOT NULL,
    actor_user_id bigint,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL
);
ALTER TABLE public.harvest_entries ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.harvest_entries_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.harvest_entry_plants (
    entry_id bigint NOT NULL,
    plt_id text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.harvest_entry_plots (
    entry_id bigint NOT NULL,
    plot_id text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.inventory_items (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    plt_id text,
    label text DEFAULT ''::text NOT NULL,
    inventory_type text DEFAULT 'seed'::text NOT NULL,
    unit text DEFAULT 'pcs'::text NOT NULL,
    created_at_ms bigint NOT NULL
);
ALTER TABLE public.inventory_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.inventory_transactions (
    id bigint NOT NULL,
    item_id bigint NOT NULL,
    delta bigint NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    source_name text DEFAULT ''::text NOT NULL,
    cost_minor bigint,
    occurred_on text NOT NULL,
    storage_location text DEFAULT ''::text NOT NULL,
    notes text DEFAULT ''::text NOT NULL,
    actor_user_id bigint,
    journal_entry_id bigint,
    created_at_ms bigint NOT NULL
);
ALTER TABLE public.inventory_transactions ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.inventory_transactions_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.layout_snapshots (
    id bigint NOT NULL,
    name text NOT NULL,
    created_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL,
    data text NOT NULL,
    garden_id bigint DEFAULT 1
);
ALTER TABLE public.layout_snapshots ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.layout_snapshots_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.layout_state (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    house_row bigint NOT NULL,
    house_col bigint NOT NULL,
    house_width bigint NOT NULL,
    house_height bigint NOT NULL,
    north_degrees bigint DEFAULT 0 NOT NULL,
    grid_rows bigint DEFAULT 30 NOT NULL,
    grid_cols bigint DEFAULT 22 NOT NULL
);
ALTER TABLE public.layout_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.layout_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.lidar_grid_cache (
    id bigint NOT NULL,
    signature text NOT NULL,
    grid_blob bytea NOT NULL,
    grid_rows bigint NOT NULL,
    grid_cols bigint NOT NULL,
    min_x double precision NOT NULL,
    max_x double precision NOT NULL,
    min_y double precision NOT NULL,
    max_y double precision NOT NULL,
    resolution_m double precision NOT NULL,
    crs_wkt text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.media_assets (
    asset_id text NOT NULL,
    garden_id bigint NOT NULL,
    storage_key text NOT NULL,
    preview_storage_key text NOT NULL,
    original_filename text DEFAULT ''::text NOT NULL,
    mime_type text NOT NULL,
    bytes bigint NOT NULL,
    width bigint NOT NULL,
    height bigint NOT NULL,
    created_at_ms bigint NOT NULL,
    actor_user_id bigint
);
CREATE TABLE IF NOT EXISTS public.media_links (
    asset_id text NOT NULL,
    target_type text NOT NULL,
    target_id text NOT NULL,
    sort_order bigint DEFAULT 0 NOT NULL
);
CREATE TABLE IF NOT EXISTS public.notification_events (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    user_id bigint,
    notification_type text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    body text DEFAULT ''::text NOT NULL,
    target_type text,
    target_id text,
    read_at_ms bigint,
    emailed_at_ms bigint,
    metadata_json text,
    dismissed bigint DEFAULT 0 NOT NULL,
    created_at_ms bigint NOT NULL
);
ALTER TABLE public.notification_events ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.notification_events_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.plant_cover_import_status (
    garden_id bigint NOT NULL,
    plt_id text NOT NULL,
    status_code text NOT NULL,
    detail text DEFAULT ''::text NOT NULL,
    attempted_at_ms bigint NOT NULL
);
CREATE TABLE IF NOT EXISTS public.plant_media_covers (
    garden_id bigint NOT NULL,
    plt_id text NOT NULL,
    asset_id text NOT NULL,
    set_at_ms bigint NOT NULL,
    set_by_user_id bigint
);
CREATE TABLE IF NOT EXISTS public.plant_ownership (
    plt_id text NOT NULL,
    owner_user_id bigint NOT NULL,
    garden_id bigint DEFAULT 1 NOT NULL
);
CREATE TABLE IF NOT EXISTS public.plants (
    plt_id text NOT NULL,
    name text NOT NULL,
    latin text,
    category text NOT NULL,
    bloom_month text,
    color text,
    hardiness text,
    height_cm bigint,
    light text,
    link text,
    year_planted text,
    seen_growing bigint,
    deer_resistant bigint DEFAULT 0 NOT NULL,
    care_watering text DEFAULT ''::text,
    care_soil text DEFAULT ''::text,
    care_planting text DEFAULT ''::text,
    care_maintenance text DEFAULT ''::text,
    care_notes text DEFAULT ''::text,
    seen_growing_date text
);
CREATE TABLE IF NOT EXISTS public.plot_elevation_overrides (
    plot_id text NOT NULL,
    elevation_m double precision NOT NULL,
    garden_id bigint DEFAULT 1
);
CREATE TABLE IF NOT EXISTS public.plot_elevations (
    plot_id text NOT NULL,
    elevation_m double precision NOT NULL,
    cache_sig text NOT NULL,
    garden_id bigint DEFAULT 1
);
CREATE TABLE IF NOT EXISTS public.plot_ownership (
    plot_id text NOT NULL,
    owner_user_id bigint NOT NULL,
    garden_id bigint DEFAULT 1
);
CREATE TABLE IF NOT EXISTS public.plot_plants (
    plot_id text NOT NULL,
    plt_id text NOT NULL,
    quantity bigint DEFAULT 1 NOT NULL,
    seen_growing bigint,
    seen_growing_date text,
    room_label text
);
CREATE TABLE IF NOT EXISTS public.plots (
    plot_id text NOT NULL,
    zone_code text NOT NULL,
    zone_name text NOT NULL,
    plot_number bigint NOT NULL,
    grid_row bigint,
    grid_col bigint,
    sub_zone text,
    notes text,
    color text
);
CREATE TABLE IF NOT EXISTS public.procurement_items (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    inventory_type text DEFAULT 'other'::text NOT NULL,
    linked_plt_id text,
    vendor_name text DEFAULT ''::text NOT NULL,
    vendor_url text DEFAULT ''::text NOT NULL,
    status text DEFAULT 'wanted'::text NOT NULL,
    cost_minor bigint DEFAULT 0 NOT NULL,
    currency text DEFAULT 'NOK'::text NOT NULL,
    quantity double precision DEFAULT 1 NOT NULL,
    unit text DEFAULT 'pieces'::text NOT NULL,
    ordered_on text,
    expected_on text,
    received_on text,
    notes text DEFAULT ''::text NOT NULL,
    metadata_json text DEFAULT '{}'::text NOT NULL,
    created_by_user_id bigint,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL,
    linked_plot_id text
);
ALTER TABLE public.procurement_items ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.procurement_items_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.provider_daily_usage (
    usage_day text NOT NULL,
    feature text NOT NULL,
    scope_type text NOT NULL,
    scope_id bigint NOT NULL,
    request_count bigint DEFAULT 0 NOT NULL,
    last_request_at_ms bigint NOT NULL
);
-- schema_migrations is created by run_migrations() before this file runs
CREATE TABLE IF NOT EXISTS public.security_runtime_flags (
    key text NOT NULL,
    value text NOT NULL,
    updated_at text DEFAULT (CURRENT_TIMESTAMP)::text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.security_telemetry_outbox (
    id bigint NOT NULL,
    event_kind text NOT NULL,
    payload_json text NOT NULL,
    created_at_ms bigint NOT NULL,
    available_at_ms bigint NOT NULL,
    attempt_count bigint DEFAULT 0 NOT NULL,
    last_error text DEFAULT ''::text NOT NULL
);
ALTER TABLE public.security_telemetry_outbox ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.security_telemetry_outbox_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.shademap_cache (
    cache_kind text NOT NULL,
    cache_key text NOT NULL,
    fetched_at_ms bigint NOT NULL,
    content_type text DEFAULT ''::text NOT NULL,
    payload_text text,
    payload_blob bytea,
    garden_id bigint DEFAULT 1
);
CREATE TABLE IF NOT EXISTS public.shademap_calibration (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    enabled bigint DEFAULT 0 NOT NULL,
    calibration_type text DEFAULT 'two-point'::text NOT NULL,
    origin_grid_col double precision,
    origin_grid_row double precision,
    origin_latitude double precision,
    origin_longitude double precision,
    axis_grid_col double precision,
    axis_grid_row double precision,
    axis_latitude double precision,
    axis_longitude double precision,
    house_nw_latitude double precision,
    house_nw_longitude double precision,
    house_ne_latitude double precision,
    house_ne_longitude double precision,
    house_se_latitude double precision,
    house_se_longitude double precision,
    house_sw_latitude double precision,
    house_sw_longitude double precision
);
ALTER TABLE public.shademap_calibration ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shademap_calibration_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.shademap_obstacles (
    id bigint NOT NULL,
    label text NOT NULL,
    kind text DEFAULT 'tree'::text NOT NULL,
    linked_plot_id text,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL,
    height_m double precision NOT NULL,
    crown_radius_m double precision NOT NULL,
    active bigint DEFAULT 1 NOT NULL,
    garden_id bigint DEFAULT 1
);
ALTER TABLE public.shademap_obstacles ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shademap_obstacles_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.shademap_state (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    mode text DEFAULT 'shadow'::text NOT NULL,
    selected_plot_id text,
    analysis_timestamp_ms bigint DEFAULT 0 NOT NULL,
    preset text DEFAULT 'now'::text NOT NULL
);
ALTER TABLE public.shademap_state ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.shademap_state_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.user_notification_preferences (
    id bigint NOT NULL,
    user_id bigint NOT NULL,
    in_app_enabled bigint DEFAULT 1 NOT NULL,
    email_enabled bigint DEFAULT 0 NOT NULL,
    email_address text DEFAULT ''::text NOT NULL,
    digest_frequency text DEFAULT 'daily'::text NOT NULL,
    quiet_hours_json text DEFAULT '{}'::text NOT NULL,
    task_due_enabled bigint DEFAULT 1 NOT NULL,
    task_overdue_enabled bigint DEFAULT 1 NOT NULL,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL,
    last_email_digest_at_ms bigint
);
ALTER TABLE public.user_notification_preferences ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_notification_preferences_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.user_saved_views (
    id bigint NOT NULL,
    user_id bigint,
    garden_id bigint NOT NULL,
    view_type text NOT NULL,
    label text DEFAULT ''::text NOT NULL,
    filter_json text DEFAULT '{}'::text NOT NULL,
    is_preset bigint DEFAULT 0 NOT NULL,
    sort_order bigint DEFAULT 0 NOT NULL,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL
);
ALTER TABLE public.user_saved_views ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.user_saved_views_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.weather_alert_plants (
    alert_id bigint NOT NULL,
    plt_id text NOT NULL
);
CREATE TABLE IF NOT EXISTS public.weather_alerts (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    alert_type text NOT NULL,
    severity text DEFAULT 'normal'::text NOT NULL,
    title text DEFAULT ''::text NOT NULL,
    description text DEFAULT ''::text NOT NULL,
    valid_from text NOT NULL,
    valid_until text NOT NULL,
    metadata_json text DEFAULT '{}'::text NOT NULL,
    dismissed bigint DEFAULT 0 NOT NULL,
    created_at_ms bigint NOT NULL
);
ALTER TABLE public.weather_alerts ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weather_alerts_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
CREATE TABLE IF NOT EXISTS public.weather_cache (
    id bigint NOT NULL,
    garden_id bigint NOT NULL,
    fetched_at_ms bigint NOT NULL,
    forecast_json text DEFAULT '{}'::text NOT NULL,
    latitude double precision NOT NULL,
    longitude double precision NOT NULL
);
ALTER TABLE public.weather_cache ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY (
    SEQUENCE NAME public.weather_cache_id_seq
    START WITH 1
    INCREMENT BY 1
    NO MINVALUE
    NO MAXVALUE
    CACHE 1
);
ALTER TABLE ONLY public.app_settings
    ADD CONSTRAINT app_settings_pkey PRIMARY KEY (key);
ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT audit_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.auth_mfa_pending_enrollments
    ADD CONSTRAINT auth_mfa_pending_enrollments_pkey PRIMARY KEY (user_id);
ALTER TABLE ONLY public.auth_mfa_recovery_codes
    ADD CONSTRAINT auth_mfa_recovery_codes_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.auth_password_reset_tokens
    ADD CONSTRAINT auth_password_reset_tokens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT auth_sessions_pkey PRIMARY KEY (token_hash);
ALTER TABLE ONLY public.auth_user_invitations
    ADD CONSTRAINT auth_user_invitations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.auth_user_plot_assignment_meanings
    ADD CONSTRAINT auth_user_plot_assignment_meanings_pkey PRIMARY KEY (user_id, pattern);
ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT auth_users_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.garden_invitations
    ADD CONSTRAINT garden_invitations_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.garden_issue_plants
    ADD CONSTRAINT garden_issue_plants_pkey PRIMARY KEY (issue_id, plt_id);
ALTER TABLE ONLY public.garden_issue_plots
    ADD CONSTRAINT garden_issue_plots_pkey PRIMARY KEY (issue_id, plot_id);
ALTER TABLE ONLY public.garden_issues
    ADD CONSTRAINT garden_issues_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.garden_journal_entries
    ADD CONSTRAINT garden_journal_entries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.garden_journal_entry_plants
    ADD CONSTRAINT garden_journal_entry_plants_pkey PRIMARY KEY (entry_id, plt_id);
ALTER TABLE ONLY public.garden_journal_entry_plots
    ADD CONSTRAINT garden_journal_entry_plots_pkey PRIMARY KEY (entry_id, plot_id);
ALTER TABLE ONLY public.garden_memberships
    ADD CONSTRAINT garden_memberships_pkey PRIMARY KEY (garden_id, user_id);
ALTER TABLE ONLY public.garden_task_plants
    ADD CONSTRAINT garden_task_plants_pkey PRIMARY KEY (task_id, plt_id);
ALTER TABLE ONLY public.garden_task_plots
    ADD CONSTRAINT garden_task_plots_pkey PRIMARY KEY (task_id, plot_id);
ALTER TABLE ONLY public.garden_tasks
    ADD CONSTRAINT garden_tasks_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.gardens
    ADD CONSTRAINT gardens_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.harvest_entries
    ADD CONSTRAINT harvest_entries_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.harvest_entry_plants
    ADD CONSTRAINT harvest_entry_plants_pkey PRIMARY KEY (entry_id, plt_id);
ALTER TABLE ONLY public.harvest_entry_plots
    ADD CONSTRAINT harvest_entry_plots_pkey PRIMARY KEY (entry_id, plot_id);
ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT inventory_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.inventory_transactions
    ADD CONSTRAINT inventory_transactions_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.layout_snapshots
    ADD CONSTRAINT layout_snapshots_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.layout_state
    ADD CONSTRAINT layout_state_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.lidar_grid_cache
    ADD CONSTRAINT lidar_grid_cache_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT media_assets_pkey PRIMARY KEY (asset_id);
ALTER TABLE ONLY public.media_links
    ADD CONSTRAINT media_links_pkey PRIMARY KEY (asset_id, target_type, target_id);
ALTER TABLE ONLY public.notification_events
    ADD CONSTRAINT notification_events_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.plant_cover_import_status
    ADD CONSTRAINT plant_cover_import_status_pkey PRIMARY KEY (garden_id, plt_id);
ALTER TABLE ONLY public.plant_media_covers
    ADD CONSTRAINT plant_media_covers_pkey PRIMARY KEY (garden_id, plt_id);
ALTER TABLE ONLY public.plant_ownership
    ADD CONSTRAINT plant_ownership_pkey PRIMARY KEY (plt_id, garden_id);
ALTER TABLE ONLY public.plants
    ADD CONSTRAINT plants_pkey PRIMARY KEY (plt_id);
ALTER TABLE ONLY public.plot_elevation_overrides
    ADD CONSTRAINT plot_elevation_overrides_pkey PRIMARY KEY (plot_id);
ALTER TABLE ONLY public.plot_elevations
    ADD CONSTRAINT plot_elevations_pkey PRIMARY KEY (plot_id);
ALTER TABLE ONLY public.plot_ownership
    ADD CONSTRAINT plot_ownership_pkey PRIMARY KEY (plot_id);
ALTER TABLE ONLY public.plot_plants
    ADD CONSTRAINT plot_plants_pkey PRIMARY KEY (plot_id, plt_id);
ALTER TABLE ONLY public.plots
    ADD CONSTRAINT plots_pkey PRIMARY KEY (plot_id);
ALTER TABLE ONLY public.procurement_items
    ADD CONSTRAINT procurement_items_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.provider_daily_usage
    ADD CONSTRAINT provider_daily_usage_pkey PRIMARY KEY (usage_day, feature, scope_type, scope_id);
-- schema_migrations PK is created by run_migrations()
ALTER TABLE ONLY public.security_runtime_flags
    ADD CONSTRAINT security_runtime_flags_pkey PRIMARY KEY (key);
ALTER TABLE ONLY public.security_telemetry_outbox
    ADD CONSTRAINT security_telemetry_outbox_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.shademap_cache
    ADD CONSTRAINT shademap_cache_pkey PRIMARY KEY (cache_kind, cache_key);
ALTER TABLE ONLY public.shademap_calibration
    ADD CONSTRAINT shademap_calibration_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.shademap_obstacles
    ADD CONSTRAINT shademap_obstacles_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.shademap_state
    ADD CONSTRAINT shademap_state_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_notification_preferences
    ADD CONSTRAINT user_notification_preferences_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.user_saved_views
    ADD CONSTRAINT user_saved_views_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.weather_alert_plants
    ADD CONSTRAINT weather_alert_plants_pkey PRIMARY KEY (alert_id, plt_id);
ALTER TABLE ONLY public.weather_alerts
    ADD CONSTRAINT weather_alerts_pkey PRIMARY KEY (id);
ALTER TABLE ONLY public.weather_cache
    ADD CONSTRAINT weather_cache_pkey PRIMARY KEY (id);
CREATE INDEX IF NOT EXISTS idx_audit_events_actor ON public.audit_events USING btree (actor_username, occurred_at_ms);
CREATE INDEX IF NOT EXISTS idx_audit_events_garden ON public.audit_events USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_audit_events_time ON public.audit_events USING btree (occurred_at_ms);
CREATE INDEX IF NOT EXISTS idx_auth_mfa_pending_expires ON public.auth_mfa_pending_enrollments USING btree (expires_at_ms);
CREATE INDEX IF NOT EXISTS idx_auth_mfa_recovery_user ON public.auth_mfa_recovery_codes USING btree (user_id, used_at_ms);
CREATE INDEX IF NOT EXISTS idx_auth_plot_meanings_user ON public.auth_user_plot_assignment_meanings USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_pw_reset_expires ON public.auth_password_reset_tokens USING btree (expires_at_ms);
CREATE INDEX IF NOT EXISTS idx_auth_pw_reset_user ON public.auth_password_reset_tokens USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_expires ON public.auth_sessions USING btree (expires_at_ms);
CREATE INDEX IF NOT EXISTS idx_auth_sessions_user ON public.auth_sessions USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_auth_user_invitations_expires ON public.auth_user_invitations USING btree (expires_at_ms);
CREATE INDEX IF NOT EXISTS idx_auth_user_invitations_invitee ON public.auth_user_invitations USING btree (invitee_username);
CREATE INDEX IF NOT EXISTS idx_garden_invitations_garden ON public.garden_invitations USING btree (garden_id, expires_at_ms);
CREATE INDEX IF NOT EXISTS idx_garden_invitations_invitee ON public.garden_invitations USING btree (invitee_username);
CREATE INDEX IF NOT EXISTS idx_garden_memberships_user ON public.garden_memberships USING btree (user_id);
CREATE INDEX IF NOT EXISTS idx_gi_follow_up ON public.garden_issues USING btree (garden_id, follow_up_on);
CREATE INDEX IF NOT EXISTS idx_gi_garden ON public.garden_issues USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_gi_status ON public.garden_issues USING btree (garden_id, status);
CREATE INDEX IF NOT EXISTS idx_gip_plt ON public.garden_issue_plants USING btree (plt_id);
CREATE INDEX IF NOT EXISTS idx_gipl_plot ON public.garden_issue_plots USING btree (plot_id);
CREATE INDEX IF NOT EXISTS idx_gje_actor ON public.garden_journal_entries USING btree (garden_id, actor_user_id);
CREATE INDEX IF NOT EXISTS idx_gje_event_type ON public.garden_journal_entries USING btree (garden_id, event_type);
CREATE INDEX IF NOT EXISTS idx_gje_garden ON public.garden_journal_entries USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_gje_occurred ON public.garden_journal_entries USING btree (garden_id, occurred_on);
CREATE INDEX IF NOT EXISTS idx_gjep_plt ON public.garden_journal_entry_plants USING btree (plt_id);
CREATE INDEX IF NOT EXISTS idx_gjepl_plot ON public.garden_journal_entry_plots USING btree (plot_id);
CREATE INDEX IF NOT EXISTS idx_gt_due ON public.garden_tasks USING btree (garden_id, due_on);
CREATE INDEX IF NOT EXISTS idx_gt_garden ON public.garden_tasks USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_gt_rule ON public.garden_tasks USING btree (garden_id, rule_source);
CREATE INDEX IF NOT EXISTS idx_gt_status ON public.garden_tasks USING btree (garden_id, status);
CREATE INDEX IF NOT EXISTS idx_gtp_plt ON public.garden_task_plants USING btree (plt_id);
CREATE INDEX IF NOT EXISTS idx_gtpl_plot ON public.garden_task_plots USING btree (plot_id);
CREATE INDEX IF NOT EXISTS idx_he_date ON public.harvest_entries USING btree (garden_id, occurred_on);
CREATE INDEX IF NOT EXISTS idx_he_garden ON public.harvest_entries USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_hep_plt ON public.harvest_entry_plants USING btree (plt_id);
CREATE INDEX IF NOT EXISTS idx_hepl_plot ON public.harvest_entry_plots USING btree (plot_id);
CREATE INDEX IF NOT EXISTS idx_inv_items_garden ON public.inventory_items USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_inv_items_plt ON public.inventory_items USING btree (garden_id, plt_id);
CREATE INDEX IF NOT EXISTS idx_inv_tx_item ON public.inventory_transactions USING btree (item_id);
CREATE INDEX IF NOT EXISTS idx_inv_tx_occurred ON public.inventory_transactions USING btree (item_id, occurred_on);
CREATE INDEX IF NOT EXISTS idx_layout_snapshots_garden ON public.layout_snapshots USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_layout_state_garden ON public.layout_state USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_media_assets_garden ON public.media_assets USING btree (garden_id, created_at_ms);
CREATE INDEX IF NOT EXISTS idx_media_links_asset ON public.media_links USING btree (asset_id);
CREATE INDEX IF NOT EXISTS idx_media_links_target ON public.media_links USING btree (target_type, target_id, sort_order);
CREATE INDEX IF NOT EXISTS idx_pi_garden ON public.procurement_items USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_pi_plant ON public.procurement_items USING btree (linked_plt_id);
CREATE INDEX IF NOT EXISTS idx_pi_status ON public.procurement_items USING btree (garden_id, status);
CREATE INDEX IF NOT EXISTS idx_plant_cover_import_status_code ON public.plant_cover_import_status USING btree (garden_id, status_code);
CREATE INDEX IF NOT EXISTS idx_plant_media_covers_asset ON public.plant_media_covers USING btree (asset_id);
CREATE INDEX IF NOT EXISTS idx_plant_ownership_garden ON public.plant_ownership USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_plant_ownership_owner ON public.plant_ownership USING btree (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_plants_name ON public.plants USING btree (name);
CREATE INDEX IF NOT EXISTS idx_plot_elevation_overrides_garden ON public.plot_elevation_overrides USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_plot_elevations_garden ON public.plot_elevations USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_plot_ownership_garden ON public.plot_ownership USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_plot_ownership_owner ON public.plot_ownership USING btree (owner_user_id);
CREATE INDEX IF NOT EXISTS idx_plots_zone ON public.plots USING btree (zone_code);
CREATE INDEX IF NOT EXISTS idx_pp_plot ON public.plot_plants USING btree (plot_id);
CREATE INDEX IF NOT EXISTS idx_pp_plt ON public.plot_plants USING btree (plt_id);
CREATE INDEX IF NOT EXISTS idx_provider_daily_usage_feature_day ON public.provider_daily_usage USING btree (usage_day, feature, scope_type, request_count, scope_id);
CREATE INDEX IF NOT EXISTS idx_security_telemetry_outbox_available ON public.security_telemetry_outbox USING btree (available_at_ms, id);
CREATE INDEX IF NOT EXISTS idx_shademap_cache_garden ON public.shademap_cache USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_shademap_cache_kind_fetched ON public.shademap_cache USING btree (cache_kind, fetched_at_ms);
CREATE INDEX IF NOT EXISTS idx_shademap_calibration_garden ON public.shademap_calibration USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_shademap_obstacles_garden ON public.shademap_obstacles USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_shademap_state_garden ON public.shademap_state USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_usv_type ON public.user_saved_views USING btree (user_id, garden_id, view_type);
CREATE INDEX IF NOT EXISTS idx_usv_user ON public.user_saved_views USING btree (user_id, garden_id);
CREATE INDEX IF NOT EXISTS idx_wa_active ON public.weather_alerts USING btree (garden_id, dismissed, valid_until);
CREATE INDEX IF NOT EXISTS idx_wa_garden ON public.weather_alerts USING btree (garden_id);
CREATE INDEX IF NOT EXISTS idx_wap_plt ON public.weather_alert_plants USING btree (plt_id);
CREATE INDEX IF NOT EXISTS idx_wc_fetched ON public.weather_cache USING btree (garden_id, fetched_at_ms);
CREATE INDEX IF NOT EXISTS idx_wc_garden ON public.weather_cache USING btree (garden_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_auth_password_reset_tokens_token_hash ON public.auth_password_reset_tokens USING btree (token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS ux_auth_user_invitations_token_hash ON public.auth_user_invitations USING btree (token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS ux_auth_users_username ON public.auth_users USING btree (username);
CREATE UNIQUE INDEX IF NOT EXISTS ux_garden_invitations_token_hash ON public.garden_invitations USING btree (token_hash);
CREATE UNIQUE INDEX IF NOT EXISTS ux_gardens_slug ON public.gardens USING btree (slug);
CREATE UNIQUE INDEX IF NOT EXISTS ux_layout_state_garden_id ON public.layout_state USING btree (garden_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_media_assets_preview_storage_key ON public.media_assets USING btree (preview_storage_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_media_assets_storage_key ON public.media_assets USING btree (storage_key);
CREATE UNIQUE INDEX IF NOT EXISTS ux_shademap_calibration_garden_id ON public.shademap_calibration USING btree (garden_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_shademap_state_garden_id ON public.shademap_state USING btree (garden_id);
CREATE UNIQUE INDEX IF NOT EXISTS ux_user_notification_preferences_user_id ON public.user_notification_preferences USING btree (user_id);
ALTER TABLE ONLY public.audit_events
    ADD CONSTRAINT fk_audit_events_actor_user_id_auth_users FOREIGN KEY (actor_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.auth_mfa_pending_enrollments
    ADD CONSTRAINT fk_auth_mfa_pending_enrollments_user_id_auth_users FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.auth_mfa_recovery_codes
    ADD CONSTRAINT fk_auth_mfa_recovery_codes_user_id_auth_users FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.auth_password_reset_tokens
    ADD CONSTRAINT fk_auth_password_reset_tokens_created_by_user__1166c2c9 FOREIGN KEY (created_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.auth_password_reset_tokens
    ADD CONSTRAINT fk_auth_password_reset_tokens_used_by_user_id__4aec334f FOREIGN KEY (used_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.auth_password_reset_tokens
    ADD CONSTRAINT fk_auth_password_reset_tokens_user_id_auth_users FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.auth_sessions
    ADD CONSTRAINT fk_auth_sessions_user_id_auth_users FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.auth_user_invitations
    ADD CONSTRAINT fk_auth_user_invitations_accepted_user_id_auth_users FOREIGN KEY (accepted_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.auth_user_invitations
    ADD CONSTRAINT fk_auth_user_invitations_created_by_user_id_auth_users FOREIGN KEY (created_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.auth_user_plot_assignment_meanings
    ADD CONSTRAINT fk_auth_user_plot_assignment_meanings_user_id__7498321a FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.auth_users
    ADD CONSTRAINT fk_auth_users_created_by_user_id_auth_users FOREIGN KEY (created_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.garden_invitations
    ADD CONSTRAINT fk_garden_invitations_accepted_user_id_auth_users FOREIGN KEY (accepted_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.garden_invitations
    ADD CONSTRAINT fk_garden_invitations_created_by_user_id_auth_users FOREIGN KEY (created_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.garden_invitations
    ADD CONSTRAINT fk_garden_invitations_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_issue_plants
    ADD CONSTRAINT fk_garden_issue_plants_issue_id_garden_issues FOREIGN KEY (issue_id) REFERENCES public.garden_issues(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_issue_plants
    ADD CONSTRAINT fk_garden_issue_plants_plt_id_plants FOREIGN KEY (plt_id) REFERENCES public.plants(plt_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_issue_plots
    ADD CONSTRAINT fk_garden_issue_plots_issue_id_garden_issues FOREIGN KEY (issue_id) REFERENCES public.garden_issues(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_issues
    ADD CONSTRAINT fk_garden_issues_created_by_user_id_auth_users FOREIGN KEY (created_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.garden_issues
    ADD CONSTRAINT fk_garden_issues_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_issues
    ADD CONSTRAINT fk_garden_issues_resolved_by_user_id_auth_users FOREIGN KEY (resolved_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.garden_journal_entries
    ADD CONSTRAINT fk_garden_journal_entries_actor_user_id_auth_users FOREIGN KEY (actor_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.garden_journal_entries
    ADD CONSTRAINT fk_garden_journal_entries_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_journal_entry_plants
    ADD CONSTRAINT fk_garden_journal_entry_plants_entry_id_garden_8b824cd6 FOREIGN KEY (entry_id) REFERENCES public.garden_journal_entries(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_journal_entry_plants
    ADD CONSTRAINT fk_garden_journal_entry_plants_plt_id_plants FOREIGN KEY (plt_id) REFERENCES public.plants(plt_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_journal_entry_plots
    ADD CONSTRAINT fk_garden_journal_entry_plots_entry_id_garden__6ff5a3d3 FOREIGN KEY (entry_id) REFERENCES public.garden_journal_entries(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_memberships
    ADD CONSTRAINT fk_garden_memberships_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_memberships
    ADD CONSTRAINT fk_garden_memberships_user_id_auth_users FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_task_plants
    ADD CONSTRAINT fk_garden_task_plants_plt_id_plants FOREIGN KEY (plt_id) REFERENCES public.plants(plt_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_task_plants
    ADD CONSTRAINT fk_garden_task_plants_task_id_garden_tasks FOREIGN KEY (task_id) REFERENCES public.garden_tasks(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_task_plots
    ADD CONSTRAINT fk_garden_task_plots_task_id_garden_tasks FOREIGN KEY (task_id) REFERENCES public.garden_tasks(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.garden_tasks
    ADD CONSTRAINT fk_garden_tasks_completed_by_user_id_auth_users FOREIGN KEY (completed_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.garden_tasks
    ADD CONSTRAINT fk_garden_tasks_created_by_user_id_auth_users FOREIGN KEY (created_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.garden_tasks
    ADD CONSTRAINT fk_garden_tasks_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.harvest_entries
    ADD CONSTRAINT fk_harvest_entries_actor_user_id_auth_users FOREIGN KEY (actor_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.harvest_entries
    ADD CONSTRAINT fk_harvest_entries_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.harvest_entry_plants
    ADD CONSTRAINT fk_harvest_entry_plants_entry_id_harvest_entries FOREIGN KEY (entry_id) REFERENCES public.harvest_entries(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.harvest_entry_plants
    ADD CONSTRAINT fk_harvest_entry_plants_plt_id_plants FOREIGN KEY (plt_id) REFERENCES public.plants(plt_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.harvest_entry_plots
    ADD CONSTRAINT fk_harvest_entry_plots_entry_id_harvest_entries FOREIGN KEY (entry_id) REFERENCES public.harvest_entries(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT fk_inventory_items_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.inventory_items
    ADD CONSTRAINT fk_inventory_items_plt_id_plants FOREIGN KEY (plt_id) REFERENCES public.plants(plt_id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.inventory_transactions
    ADD CONSTRAINT fk_inventory_transactions_actor_user_id_auth_users FOREIGN KEY (actor_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.inventory_transactions
    ADD CONSTRAINT fk_inventory_transactions_item_id_inventory_items FOREIGN KEY (item_id) REFERENCES public.inventory_items(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.inventory_transactions
    ADD CONSTRAINT fk_inventory_transactions_journal_entry_id_gar_38264bdc FOREIGN KEY (journal_entry_id) REFERENCES public.garden_journal_entries(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.layout_state
    ADD CONSTRAINT fk_layout_state_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT fk_media_assets_actor_user_id_auth_users FOREIGN KEY (actor_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.media_assets
    ADD CONSTRAINT fk_media_assets_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.media_links
    ADD CONSTRAINT fk_media_links_asset_id_media_assets FOREIGN KEY (asset_id) REFERENCES public.media_assets(asset_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.notification_events
    ADD CONSTRAINT fk_notification_events_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.notification_events
    ADD CONSTRAINT fk_notification_events_user_id_auth_users FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plant_cover_import_status
    ADD CONSTRAINT fk_plant_cover_import_status_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plant_media_covers
    ADD CONSTRAINT fk_plant_media_covers_asset_id_media_assets FOREIGN KEY (asset_id) REFERENCES public.media_assets(asset_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plant_media_covers
    ADD CONSTRAINT fk_plant_media_covers_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plant_media_covers
    ADD CONSTRAINT fk_plant_media_covers_plt_id_plants FOREIGN KEY (plt_id) REFERENCES public.plants(plt_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plant_media_covers
    ADD CONSTRAINT fk_plant_media_covers_set_by_user_id_auth_users FOREIGN KEY (set_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.plant_ownership
    ADD CONSTRAINT fk_plant_ownership_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plant_ownership
    ADD CONSTRAINT fk_plant_ownership_owner_user_id_auth_users FOREIGN KEY (owner_user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plant_ownership
    ADD CONSTRAINT fk_plant_ownership_plt_id_plants FOREIGN KEY (plt_id) REFERENCES public.plants(plt_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plot_elevation_overrides
    ADD CONSTRAINT fk_plot_elevation_overrides_plot_id_plots FOREIGN KEY (plot_id) REFERENCES public.plots(plot_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plot_elevations
    ADD CONSTRAINT fk_plot_elevations_plot_id_plots FOREIGN KEY (plot_id) REFERENCES public.plots(plot_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plot_ownership
    ADD CONSTRAINT fk_plot_ownership_owner_user_id_auth_users FOREIGN KEY (owner_user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plot_ownership
    ADD CONSTRAINT fk_plot_ownership_plot_id_plots FOREIGN KEY (plot_id) REFERENCES public.plots(plot_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.plot_plants
    ADD CONSTRAINT fk_plot_plants_plt_id_plants FOREIGN KEY (plt_id) REFERENCES public.plants(plt_id) DEFERRABLE;
ALTER TABLE ONLY public.procurement_items
    ADD CONSTRAINT fk_procurement_items_created_by_user_id_auth_users FOREIGN KEY (created_by_user_id) REFERENCES public.auth_users(id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.procurement_items
    ADD CONSTRAINT fk_procurement_items_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.procurement_items
    ADD CONSTRAINT fk_procurement_items_linked_plt_id_plants FOREIGN KEY (linked_plt_id) REFERENCES public.plants(plt_id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.shademap_calibration
    ADD CONSTRAINT fk_shademap_calibration_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.shademap_obstacles
    ADD CONSTRAINT fk_shademap_obstacles_linked_plot_id_plots FOREIGN KEY (linked_plot_id) REFERENCES public.plots(plot_id) ON DELETE SET NULL DEFERRABLE;
ALTER TABLE ONLY public.shademap_state
    ADD CONSTRAINT fk_shademap_state_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.user_notification_preferences
    ADD CONSTRAINT fk_user_notification_preferences_user_id_auth_users FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.user_saved_views
    ADD CONSTRAINT fk_user_saved_views_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.user_saved_views
    ADD CONSTRAINT fk_user_saved_views_user_id_auth_users FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.weather_alert_plants
    ADD CONSTRAINT fk_weather_alert_plants_alert_id_weather_alerts FOREIGN KEY (alert_id) REFERENCES public.weather_alerts(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.weather_alert_plants
    ADD CONSTRAINT fk_weather_alert_plants_plt_id_plants FOREIGN KEY (plt_id) REFERENCES public.plants(plt_id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.weather_alerts
    ADD CONSTRAINT fk_weather_alerts_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;
ALTER TABLE ONLY public.weather_cache
    ADD CONSTRAINT fk_weather_cache_garden_id_gardens FOREIGN KEY (garden_id) REFERENCES public.gardens(id) ON DELETE CASCADE DEFERRABLE;

INSERT INTO schema_migrations (version) VALUES (1) ON CONFLICT DO NOTHING;
