CREATE TABLE IF NOT EXISTS public.auth_passkeys (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    credential_id text NOT NULL,
    credential_public_key text NOT NULL,
    sign_count bigint DEFAULT 0 NOT NULL,
    nickname text DEFAULT ''::text NOT NULL,
    transports text DEFAULT ''::text NOT NULL,
    credential_device_type text DEFAULT ''::text NOT NULL,
    credential_backed_up bigint DEFAULT 0 NOT NULL,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL,
    last_used_at_ms bigint,
    FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_auth_passkeys_credential_id
    ON public.auth_passkeys (credential_id);

CREATE INDEX IF NOT EXISTS idx_auth_passkeys_user
    ON public.auth_passkeys (user_id);

CREATE TABLE IF NOT EXISTS public.auth_passkey_challenges (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    token_hash text NOT NULL,
    challenge text NOT NULL,
    flow text NOT NULL,
    user_id bigint,
    session_token_hash text,
    created_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    used_at_ms bigint,
    FOREIGN KEY (user_id) REFERENCES public.auth_users(id) ON DELETE CASCADE
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_auth_passkey_challenges_token_hash
    ON public.auth_passkey_challenges (token_hash);

CREATE INDEX IF NOT EXISTS idx_auth_passkey_challenges_expires
    ON public.auth_passkey_challenges (expires_at_ms);

CREATE INDEX IF NOT EXISTS idx_auth_passkey_challenges_user
    ON public.auth_passkey_challenges (user_id, expires_at_ms);
