CREATE TABLE IF NOT EXISTS public.garden_map_objects (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id text NOT NULL UNIQUE,
    garden_id bigint NOT NULL,
    object_type text NOT NULL,
    name text NOT NULL,
    shape_type text NOT NULL,
    geometry_json text NOT NULL,
    style_json text NOT NULL,
    z_index bigint DEFAULT 0 NOT NULL,
    has_internal_layout bigint DEFAULT 0 NOT NULL,
    internal_layout_json text DEFAULT '{}'::text NOT NULL,
    created_by_user_id bigint,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL,
    CONSTRAINT fk_garden_map_objects_garden_id_gardens
        FOREIGN KEY (garden_id)
        REFERENCES public.gardens(id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_garden_map_objects_created_by_auth_users
        FOREIGN KEY (created_by_user_id)
        REFERENCES public.auth_users(id)
        ON DELETE SET NULL
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ck_garden_map_objects_internal_layout_bool
        CHECK (has_internal_layout IN (0, 1))
);

CREATE UNIQUE INDEX IF NOT EXISTS ux_garden_map_objects_id_garden
    ON public.garden_map_objects USING btree (id, garden_id);

CREATE INDEX IF NOT EXISTS idx_garden_map_objects_garden
    ON public.garden_map_objects USING btree (garden_id, z_index, id);

CREATE TABLE IF NOT EXISTS public.garden_map_object_units (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id text NOT NULL UNIQUE,
    garden_id bigint NOT NULL,
    map_object_id bigint NOT NULL,
    unit_type text NOT NULL,
    name text NOT NULL,
    shape_type text NOT NULL,
    geometry_json text NOT NULL,
    style_json text NOT NULL,
    sort_order bigint DEFAULT 0 NOT NULL,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL,
    CONSTRAINT fk_garden_map_object_units_garden_id_gardens
        FOREIGN KEY (garden_id)
        REFERENCES public.gardens(id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_garden_map_object_units_object_garden
        FOREIGN KEY (map_object_id, garden_id)
        REFERENCES public.garden_map_objects(id, garden_id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_garden_map_object_units_object
    ON public.garden_map_object_units USING btree (map_object_id, sort_order, id);

CREATE INDEX IF NOT EXISTS idx_garden_map_object_units_garden
    ON public.garden_map_object_units USING btree (garden_id);
