CREATE TABLE IF NOT EXISTS public.user_attention_preferences (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    preset text DEFAULT 'balanced'::text NOT NULL,
    rules_json text DEFAULT '{}'::text NOT NULL,
    quiet_hours_json text DEFAULT '{}'::text NOT NULL,
    show_no_action_history bigint DEFAULT 1 NOT NULL,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL,
    CONSTRAINT ux_user_attention_preferences_user UNIQUE (user_id),
    CONSTRAINT fk_user_attention_preferences_user
        FOREIGN KEY (user_id)
        REFERENCES public.auth_users(id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT ck_user_attention_preferences_no_action_bool
        CHECK (show_no_action_history IN (0, 1))
);

CREATE TABLE IF NOT EXISTS public.user_attention_item_state (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    user_id bigint NOT NULL,
    garden_id bigint NOT NULL,
    item_id text NOT NULL,
    user_state text NOT NULL,
    snoozed_until_ms bigint,
    reason text DEFAULT ''::text NOT NULL,
    metadata_json text DEFAULT '{}'::text NOT NULL,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL,
    CONSTRAINT ux_user_attention_item_state_user_garden_item UNIQUE (user_id, garden_id, item_id),
    CONSTRAINT fk_user_attention_item_state_user
        FOREIGN KEY (user_id)
        REFERENCES public.auth_users(id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED,
    CONSTRAINT fk_user_attention_item_state_garden
        FOREIGN KEY (garden_id)
        REFERENCES public.gardens(id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_user_attention_item_state_garden_user
    ON public.user_attention_item_state USING btree (
        garden_id,
        user_id,
        user_state,
        snoozed_until_ms
    );

CREATE TABLE IF NOT EXISTS public.attention_outcomes (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    public_id text NOT NULL UNIQUE,
    garden_id bigint NOT NULL,
    provider text NOT NULL,
    outcome_type text NOT NULL,
    source_type text NOT NULL,
    source_id text DEFAULT ''::text NOT NULL,
    source_public_id text DEFAULT ''::text NOT NULL,
    title text NOT NULL,
    explanation text NOT NULL,
    reason text DEFAULT ''::text NOT NULL,
    target_type text DEFAULT ''::text NOT NULL,
    target_id text DEFAULT ''::text NOT NULL,
    plant_ids_json text DEFAULT '[]'::text NOT NULL,
    plot_ids_json text DEFAULT '[]'::text NOT NULL,
    recovery_action_json text DEFAULT '{}'::text NOT NULL,
    metadata_json text DEFAULT '{}'::text NOT NULL,
    occurred_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    created_at_ms bigint NOT NULL,
    updated_at_ms bigint NOT NULL,
    CONSTRAINT fk_attention_outcomes_garden
        FOREIGN KEY (garden_id)
        REFERENCES public.gardens(id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_attention_outcomes_garden_expires
    ON public.attention_outcomes USING btree (
        garden_id,
        expires_at_ms DESC,
        occurred_at_ms DESC
    );

CREATE INDEX IF NOT EXISTS idx_attention_outcomes_source
    ON public.attention_outcomes USING btree (garden_id, provider, source_type, source_id);

CREATE UNIQUE INDEX IF NOT EXISTS ux_attention_outcomes_source_kind
    ON public.attention_outcomes USING btree (
        garden_id,
        provider,
        outcome_type,
        source_type,
        source_public_id,
        target_type,
        target_id
    );
