-- Offline operation records survive target deletion for the full retry window.
-- They deliberately reference only the garden: target rows must not cascade away
-- the idempotency key before a client can resolve a lost acknowledgement.

CREATE TABLE IF NOT EXISTS public.offline_create_operations (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    garden_id bigint NOT NULL,
    endpoint text NOT NULL,
    operation_id text NOT NULL,
    request_fingerprint text NOT NULL,
    target_type text NOT NULL,
    target_id text NOT NULL,
    result_id text NOT NULL,
    created_at_ms bigint NOT NULL,
    expires_at_ms bigint NOT NULL,
    CONSTRAINT ux_offline_create_operations_garden_endpoint_operation
        UNIQUE (garden_id, endpoint, operation_id),
    CONSTRAINT ck_offline_create_operations_endpoint_target
        CHECK (
            (endpoint = 'journal' AND target_type = 'journal_entry' AND target_id = result_id)
            OR (endpoint = 'issues' AND target_type = 'issue' AND target_id = result_id)
            OR (endpoint = 'harvest' AND target_type = 'harvest_entry' AND target_id = result_id)
            OR (endpoint = 'task_action' AND target_type = 'task' AND target_id = result_id)
            OR (
                endpoint = 'media_upload'
                AND target_type IN ('journal_entry', 'issue', 'harvest_entry', 'plant', 'plot')
            )
        ),
    CONSTRAINT ck_offline_create_operations_operation_id_length
        CHECK (char_length(operation_id) BETWEEN 1 AND 128),
    CONSTRAINT ck_offline_create_operations_target_id_length
        CHECK (char_length(target_id) BETWEEN 1 AND 120),
    CONSTRAINT ck_offline_create_operations_result_id_length
        CHECK (char_length(result_id) BETWEEN 1 AND 120),
    CONSTRAINT ck_offline_create_operations_request_fingerprint
        CHECK (request_fingerprint ~ '^[0-9a-f]{64}$'),
    CONSTRAINT ck_offline_create_operations_expiry
        CHECK (expires_at_ms > created_at_ms),
    CONSTRAINT fk_offline_create_operations_garden
        FOREIGN KEY (garden_id)
        REFERENCES public.gardens(id)
        ON DELETE CASCADE
        DEFERRABLE INITIALLY DEFERRED
);

CREATE INDEX IF NOT EXISTS idx_offline_create_operations_expiry
    ON public.offline_create_operations USING btree (expires_at_ms);
