ALTER TABLE public.media_assets
    ADD COLUMN IF NOT EXISTS preview_bytes bigint NOT NULL DEFAULT 0;

CREATE TABLE IF NOT EXISTS public.media_cleanup_jobs (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    storage_key text NOT NULL,
    preview_storage_key text NOT NULL,
    attempts integer NOT NULL DEFAULT 0,
    last_error text NOT NULL DEFAULT '',
    created_at_ms bigint NOT NULL,
    last_attempt_at_ms bigint,
    CONSTRAINT ux_media_cleanup_jobs_storage_keys
        UNIQUE (storage_key, preview_storage_key),
    CONSTRAINT ck_media_cleanup_jobs_attempts_nonnegative
        CHECK (attempts >= 0)
);

CREATE INDEX IF NOT EXISTS idx_media_cleanup_jobs_created
    ON public.media_cleanup_jobs (created_at_ms, id);
