import assert from 'node:assert/strict';
import { cacheTaskList, getCachedTaskList, getCachedTodayTasks } from '../frontend/src/services/taskCache.ts';

const task = (id, plot, status = 'pending', task_type = 'water') => ({ id, plot_ids: [plot], status, task_type });
const a = task('a', 'A');
const b = task('b', 'B');
cacheTaskList(1, { plot_id: 'A', view: 'today' }, { tasks: [a], total: 1 });
assert.equal(getCachedTaskList(1, { plot_id: 'B', view: 'today' }), null);
assert.equal(getCachedTaskList(1, { view: 'today' }), null);
assert.equal(getCachedTodayTasks(1), null);
assert.deepEqual(getCachedTaskList(1, { view: 'today', plot_id: 'A' }).tasks, [a]);
assert.equal(getCachedTaskList(1, { view: 'today', plot_id: 'A', limit: 1 }), null);
const c = task('c', 'B', 'completed');
cacheTaskList(2, { limit: 50, offset: 0 }, { tasks: [a, b, c], total: 3 });
assert.deepEqual(getCachedTaskList(2, { plot_id: 'B', limit: 1, offset: 1 }), { tasks: [c], total: 2 });
assert.deepEqual(getCachedTaskList(2, { plot_id: 'B', status: 'pending', task_type: 'water' }), { tasks: [b], total: 1 });
assert.deepEqual(getCachedTaskList(2, { status: 'completed', task_type: 'prune' }), { tasks: [], total: 0 });
assert.equal(getCachedTaskList(2, { plant_id: 'unknown' }), null);
assert.equal(getCachedTaskList(2, { view: 'today' }), null);
cacheTaskList(3, { limit: 1 }, { tasks: [a], total: 2 });
assert.equal(getCachedTaskList(3, { limit: 2 }), null);
cacheTaskList(4, { offset: 1 }, { tasks: [b], total: 1 });
assert.equal(getCachedTaskList(4, { offset: 0 }), null);
assert.equal(getCachedTaskList(5, {}), null);
cacheTaskList(6, { view: 'today' }, { tasks: [a], total: 1 });
assert.equal(getCachedTaskList(6, { view: 'today', status: 'completed' }), null);
assert.equal(getCachedTaskList(6, { view: 'today', status: 'skipped' }), null);
assert.deepEqual(getCachedTaskList(6, { view: 'today', status: 'pending' }), { tasks: [a], total: 1 });
assert.deepEqual(getCachedTaskList(2, { task_type: ' prune, water, ' }), { tasks: [a, b, c], total: 3 });
assert.deepEqual(getCachedTaskList(2, { task_type: ', , ' }), { tasks: [a, b, c], total: 3 });
console.log('task cache scope, completeness, filtering and pagination passed');
